language: python

python:
- 3.7

dist: xenial

env:
  - DJANGO="Django>=2.1,<2.2"

install:
  - pip install -U coverage codecov
  - pip install -U flake8==3.6.0
  - pip install -U $DJANGO
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then pip install black; fi
  - pip freeze

script:
  - flake8 sample_project
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then black --check sample_project; fi
  - coverage run setup.py test


after_success: codecov